# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textbox', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='published_date')),
            ],
        ),
    ]
